### ISSUE TITLE
Triangulation failure on wasm

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#297] opened 2022-12-23 08:10 UTC
It seems that the behavior on wasm is slightly different from native, which causes a weird triangulation bug that only occur on wasm but not on native. I've been testing this to find the cause of non-manifoldness and weird genus for my model when written in typescript.

```c++
TEST(Boolean, UnionWarp) {
  glm::ivec3 keys[] = {
    {1, -1, -1},
    {1, -1, 1},
    {1, 1, -1},
    {1, 1, 1},
    {-1, -1, -1},
    {-1, -1, 1},
    {-1, 1, -1},
    {-1, 1, 1}};
  glm::vec3 val1[] = {
    {-31.15,28.135,1.353},
    {-28.426,27.432,8.842},
    {-36.195,31.394,-0.573},
    {-34.85,30.694,3.128},

    {-37.452,27.928,4.975},
    {-32.32,27.304,11.08},
    {-41.304,31.061,2.323},
    {-38.753,30.44,5.341},
  };
  glm::vec3 val2[] = {
    {-37.452,27.928,4.975},
    {-32.32,27.304,11.08},
    {-41.304,31.061,2.323},
    {-38.753,30.44,5.341},

    {-50.49,27.203,15.861},
    {-45.357,26.579,21.966},
    {-54.385,29.619,13.085},
    {-51.834,28.998,16.102},
  };
  Manifold solid1 = Manifold::Cube(glm::vec3(2.0), true).Warp([&](glm::vec3 &v) {
    glm::ivec3 rounded = glm::ivec3(v);
    for (int i = 0; i < 8; i++)
      if (rounded == keys[i])
        for (int j : {0, 1, 2})
          v[j] = val1[i][j];
  });
  Manifold solid2 = Manifold::Cube(glm::vec3(2.0), true).Warp([&](glm::vec3 &v) {
    glm::ivec3 rounded = glm::ivec3(v);
    for (int i = 0; i < 8; i++)
      if (rounded == keys[i])
        for (int j : {0, 1, 2})
          v[j] = val2[i][j];
  });
  EXPECT_TRUE(solid1.IsManifold());
  EXPECT_TRUE(solid1.MatchesTriNormals());
  EXPECT_TRUE(solid2.IsManifold());
  EXPECT_TRUE(solid2.MatchesTriNormals());

  EXPECT_TRUE((solid1+solid2).IsManifold());
  EXPECT_EQ((solid1+solid2).Genus(), 0);
}
```

When run with native, the test passed without any error. But when run with wasm (with `-DMANIFOLD_DEBUG=1`), it will throw the following error:
```
[ RUN      ] Boolean.UnionWarp
-----------------------------------
Triangulation failed! Precision = 0.00054384995
Error in file: /home/pca006132/code/manifold/src/polygon/src/polygon.cpp (819): 'skipped.empty() || !vert->IsPast(skipped.back(), precision_)' is false: Not Geometrically Valid! None of the skipped verts is valid.
polys.push_back({
    {glm::vec2(27.9279995, 4.9749999), 4},  //
    {glm::vec2(31.0610008, 2.32299995), 6},  //
    {glm::vec2(31.0610008, 2.32299995), 18},  //
    {glm::vec2(27.9279995, 4.9749999), 16},  //
    {glm::vec2(27.9279995, 4.9749999), 15},  //
    {glm::vec2(31.0610008, 2.32299995), 28},  //
    {glm::vec2(30.4400005, 5.34100008), 17},  //
});
array([
  [27.9279995, 4.9749999],
  [31.0610008, 2.32299995],
  [31.0610008, 2.32299995],
  [27.9279995, 4.9749999],
  [27.9279995, 4.9749999],
  [31.0610008, 2.32299995],
  [30.4400005, 5.34100008],
])
produced this triangulation:
unknown file: Failure
C++ exception with description "Error in file: /home/pca006132/code/manifold/src/polygon/src/polygon.cpp (819): 'skipped.empty() || !vert->IsPast(skipped.back(), precision_)' is false: Not Geometrically Valid! None of the skipped verts is valid." thrown in the test body.
[  FAILED  ] Boolean.UnionWarp (6 ms)
```

**Comment by elalish** [comment] 2022-12-27 20:18
Okay, I have a sort-of repro of this now, but it seems that the only problem is a geometric check failing (rather than manifoldness) which we should be robust to be default. It turns out we were not, which I've just fixed in #299. Would you mind pulling that branch and see if that fixes your underlying issue?

**Comment by pca006132** [comment] 2022-12-27 20:30
Interesting! I just tried debugging that and I thought the reason is due to FIFO violation, but my fix will cause error to `Polygon.BigSponge` for some reason... I guess the stl implementation for priority queue is different for mac/wasm/linux.

**Comment by elalish** [comment] 2022-12-27 20:41
Hmm, actually my #299 is less necessary than I thought. But my original question remains, which is does your original issue on wasm happen if you don't compile with `MANIFOLD_DEBUG`? Does it actually error out or create ugly output? Because there will always be some narrowly-overlapped cases, but we should be robust to them as long as we're not in debug mode.

**Comment by pca006132** [comment] 2022-12-27 20:54
It will not error out for this particular case, but when combined with other operations the result is no longer a manifold. I can try to rerun the test for the whole thing.

**Comment by pca006132** [comment] 2022-12-27 21:20
Hmmm I somehow forgot what error did I get previously, but one way to see the problem is to smooth the result and refine, which will give something obviously non-manifold, although that could be a bug in refine.

**Comment by elalish** [comment] 2022-12-28 02:19
Is that refine issue also only on the WASM-debug build or more general? Probably worth filing a separate issue for that - I'm not sure how to repro.

**Comment by pca006132** [comment] 2022-12-28 04:02
WASM release build, haven't yet tried native. Will open another issue for that as well.

**Comment by pca006132** [comment] 2022-12-30 17:19
OK another issue with this is that the generated mesh is not water tight: there are 4 triangles in the connecting face (inside the mesh).

![image](https://user-images.githubusercontent.com/12198657/210095431-48abe8f2-4edf-4dfe-b2cf-3d12d7d82bd2.png)
(cura mesh-tools x-ray view)

Not sure if this is intended behavior and whether this is problematic. I tried viewing with meshlab after exporting this as obj but meshlab reports no boundary faces/edges or non-manifold vertices/edges. I guess the edges will become non-manifold edges if the vertices are deduplicated?

**Comment by elalish** [comment] 2023-01-01 18:37
I'm not quite following. I believe `Manifold` and Meshlab are in agreement that the mesh is in fact watertight/manifold. And yes, deduplicating vertices will often result in non-manifold meshes, hence why STL cannot represent a manifold reliably. So the question is, what was the expected result here and what is undesirable about the result we got?

**Comment by pca006132** [comment] 2023-01-02 05:58
The problem is that there is a seam in the middle when the two faces are exactly the same. Actually the code is the same as in #304:
```python
import trimesh
from pymanifold import Manifold

def export(model, filename, extension='obj'):
    mesh = model.to_mesh()
    meshOut = trimesh.Trimesh(
        vertices=mesh.vert_pos, faces=mesh.tri_verts)
    trimesh.exchange.export.export_mesh(meshOut, f'{filename}.{extension}', extension)

def warpFun(v):
    v = list(v)
    if all(abs(x - 1) < 0.01 for x in v):
        v[0] -= 0.5
    return v

cube1 = Manifold.cube()
cube2 = cube1.translate(1, 0, 0)
cube1 = cube1.warp(warpFun).rotate(10, 0, 0)
cube2 = cube2.warp(warpFun).rotate(10, 0, 0)
result = cube1 + cube2
```

If we remove the rotate call, the result mesh will have 12 faces, indicating the joining faces are the same. But with the rotate call, the result mesh have 16 faces, the 4 faces that were eliminated are now kept.

**Comment by elalish** [comment] 2023-01-02 07:10
Okay, so there's no triangulation error and there's no manifoldness error, just a marginal situation where two adjacent cubes don't get joined sometimes? I don't particularly consider that a bug. We do some best effort to make common situations work better, but in general we look at vertex positions as having fundamental uncertainty from rounding error and so any &epsilon;-perturbation is a valid result. I'm tempted to call this expected behavior.

**Comment by elalish** [comment] 2023-01-13 15:45
I would guess that's because `MANIFOLD_DEBUG` was also defaulting to `processOverlaps = false`, which I think is the actual source of the problem. That can be useful to debugging triangulator errors, but in general I consider the overlap failures to be warnings rather than errors, unless the result is also visually wrong.

**Closed** 2023-02-23 18:05 UTC
Labels: bug
