### ISSUE TITLE
Memory leak problem

### ISSUE THREAD

**Issue by chpark1111** [elalish/manifold#245] opened 2022-10-15 06:39 UTC
Hi, I was using this library to do following operations using the python bindings provided by this repository.

I think the memory leaks when the mesh triangularization fails.. Is there a way to fix this?

**Comment by pca006132** [comment] 2022-10-16 00:27
Hi, it would be nice if you can give a minimal example showing the leak.

**Comment by chpark1111** [comment] 2022-10-16 04:46
`manifolds = []
for i in range(50):
    pts = abs(np.random.normal(0, 0.1, 3))
    length = np.random.normal(0, 0.1, 3)
    manifolds.append(
        Manifold.cube(pts[0], pts[1], pts[2]).rotate(length[0], length[1], length[2])
    )

# st = time.time()
# mesh = c.to_mesh()
# meshOut = trimesh.Trimesh(vertices=mesh.vert_pos, faces=mesh.tri_verts)
# print(meshOut.volume)
# print("mesh time", time.time() - st)
# trimesh.exchange.export.export_mesh(meshOut, "./tmp/test.obj", "obj")

@profile(precision=5)
def my_func():
    c = manifolds[0]
    for i in range(1, len(manifolds)):
        c = c + manifolds[i]
    st = time.time()
    process = psutil.Process(os.getpid())
    print("1", process.memory_info().rss)
    for i in range(50):
        c -= manifolds[i]
        try: 
            mesh = c.to_mesh()
        except RuntimeError:
            pass
        # print(mesh)
        # meshOut = trimesh.Trimesh(vertices=mesh.vert_pos, faces=mesh.tri_verts)
        # print(meshOut.volume)
        c +=manifolds[i]
    process = psutil.Process(os.getpid())
    print("2", process.memory_info().rss)
    print("mesh vol", time.time() - st)
for k in range(10000):
    my_func()`

When I run this code and compile it with debug=OFF, the mesh vol time printed out increases and the memory usage keep increases. So, I thought this was because of the memory leak.. (I checked that memory increase was coming from to_mesh function)

**Comment by elalish** [comment] 2022-10-16 15:48
Thanks for the repro! Our python bindings are still a bit alpha, so I imagine we have a few things to fix yet. Since I'm not so familiar with python, where would you expect the memory to be cleaned up? Given your recursive function, it seems like a new `c` would stay in memory for each invocation of `my_func` until termination (I'm assuming here that each invocation of `my_func` gets its own execution context, which is how it works in other languages). Does the behavior change if `my_func` is called in a for loop instead?

**Comment by chpark1111** [comment] 2022-10-16 15:58
Nope! I shows the same behavior I just functioned to use the memory profiler which is one of the python libraries. I debuged and found out that if we don't use the c.to_mesh(), the memory usages does not increase. So, I'm suspecting the C++ implementation with GetMesh have some leaks. Also, it's not the fault of the pybind module because if I call other things or return other variables without using the manifold::GetMesh function, it does not behave like that. When I comment out the part CsgOpNode::BatchUnion, the memory leak does not happen. So, I guess these parts + triangularization part can be the problem.
Also, when compile this with CUDA support and run test/manifolds provided by the repo, it kind of leaves some unfreed memories in the GPU. So maybe this can be related to my issue.

**Comment by pca006132** [comment] 2022-10-16 16:09
I think the skipped vertices should be freed automatically as they are being stored in `std::list`, and some for other data structure. It might be possible that my `ManagedVec` implementation may leak some memory but I am not entirely sure. Maybe we can try to reproduce this in C++ directly and use valgrind to have a look at the leak.

**Comment by chpark1111** [comment] 2022-10-16 16:48
Thanks for the suggestion! I'll try to make them with C++ and check if it reproduces the result and the leaks.

**Comment by chpark1111** [comment] 2022-10-18 10:46
I think I found the problem! I think it's not the leaks but the behavior of the program.
```
int main(int argc, char **argv) {
	random_device rd;
	default_random_engine gen{ rd() };

	uniform_real_distribution<double> len_dist{0, 0.1};
	uniform_int_distribution<int> rot_dist{-180, 180};

	vector<manifold::Manifold> manifolds;
	for(int i=0;i<50;i++) {
		double len1 = len_dist(gen), len2 = len_dist(gen), len3 = len_dist(gen);
		int rot1 = rot_dist(gen), rot2 = rot_dist(gen), rot3 = rot_dist(gen);

		manifolds.push_back(manifold::Manifold::Cube(glm::vec3(len1, len2, len3)));
	}

	for (int k=0;k<200;k++) {
		manifold::Manifold c = manifolds[0];
		for(int i=1;i<50;i++)
			c = c + manifolds[i];

		for(int i=1;i<100;i++)
			manifold::Mesh nw = c.manifold::Manifold::GetMesh();

		// cout<<k<<endl;
	}
	
	// RUN_ALL_TESTS();

	return 0;
}
```
If uses the different amount of memory depending on the number of iterations it does.
Below is the valgrind report of iteration (k<3) and (k<200).
(k<3)
```
==2559273== HEAP SUMMARY:
==2559273==     in use at exit: 0 bytes in 0 blocks
==2559273==   total heap usage: 161,038 allocs, 161,038 frees, 40,932,731 bytes allocated
==2559273== 
==2559273== All heap blocks were freed -- no leaks are possible
==2559273== 
==2559273== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
(k<200)
```
==2542646== HEAP SUMMARY:
==2542646==     in use at exit: 0 bytes in 0 blocks
==2542646==   total heap usage: 9,003,669 allocs, 9,003,669 frees, 3,765,234,371 bytes allocated
==2542646== 
==2542646== All heap blocks were freed -- no leaks are possible
==2542646== 
==2542646== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
To my perspective, I think the memory usage should not increase depending on the number of total k iterations. Is this not true? I think this library does not frees local object when they are not referenced.

**Comment by pentacular** [comment] 2022-10-18 14:26
Your example looks like it is accumulating complexity with c = c + manifolds[i].

Try printing out the number of vertices and triangles after each accumulation.

**Comment by chpark1111** [comment] 2022-10-18 14:47
I checked that the mesh are consistent (Have the same number of vertices in the all the iterations). Also, I checked that with valgrind that the memory increase is coming from the GetMesh() function. So, I think that's not the case.

**Comment by pca006132** [comment] 2022-10-19 02:05
> I checked that the mesh are consistent. (Have the same number of vertices in the all the iterations) And tried to copy the manifold with AsOriginal() when assigning to c but didn't work. Also, I checked that with valgrind that the memory increase is coming from the GetMesh() function. So, I think that's not the case.

We perform lazy evaluation in `csg_tree`, it will not evaluate the mesh until you run `GetMesh()`, so memory only increases after running `GetMesh()` makes sense. I'm afraid you still need to dump the content of the `csg_tree` to check if there is anything that retained references to `c` or something.

**Comment by pentacular** [comment] 2022-10-19 03:43
Unless c and manifolds[i] are identical, then you should expect c = c + manifolds[i] to increase the complexity of c.

So if the number of vertices does not change for this case, you should be suspicious of your measurement.

**Comment by chpark1111** [comment] 2022-10-19 04:41
> Unless c and manifolds[i] are identical, then you should expect c = c + manifolds[i] to increase the complexity of c.
> 
> So if the number of vertices does not change for this case, you should be suspicious of your measurement.

I think you misunderstood the point here. Of course c's complexity increase when doing c = c + manifolds[i]'s operation. But the point is that when we escape the outer for loop (k), c is not freed completely freed.

**Comment by pentacular** [comment] 2022-10-19 04:48
You shouldn't expect the C++ heap size to be reduced by freeing memory -- generally you should just expect it to become available for reuse.

The valgrind output above supports this case -- it reports no leaks.

**Comment by pca006132** [comment] 2022-10-19 14:29
Nice finding. I think should be fixed by using a map instead of a vector to map the IDs, presumably most of the used IDs are not present in the current mesh.

@elalish what do you think?

**Comment by elalish** [comment] 2022-10-19 14:55
Yes, that sounds reasonable to me. I'm a little surprised this was noticeable; wouldn't `includesMeshIDs` have a length equal roughly to the number of meshes? Still, agreed that a map would be better.

**Comment by chpark1111** [comment] 2022-10-19 15:02
Oh, I think map is the right chose. It's hard to track all the mesh numbers with vector design when meshes are randomly allocated and freed.

**Comment by elalish** [comment] 2022-11-11 15:51
@chpark1111 Any luck making a PR?

**Comment by pca006132** [comment] 2022-11-11 16:18
I can work on this and also port make the hashtable more general.

**Comment by chpark1111** [comment] 2022-11-11 16:22
Oh I got distracted by some other project while working on it. Since I didn't make any meaningful changes yet maybe @pca006132  can work on it!

**Closed** 2022-11-17 09:55 UTC
