### ISSUE TITLE
NumTri returns uint32_t, while array uses size_t (like uint64_t or int64_t)

### ISSUE THREAD

**Issue by fire** [elalish/manifold#864] opened 2024-07-13 17:33 UTC
Was getting casting errors on ios in my code.

`uint32_t NumTri() const`

**Comment by fire** [comment] 2024-07-13 17:34
It might be user error on my side.

**Comment by elalish** [comment] 2024-07-13 20:14
@pca006132 has been working to update us to allow for more than 32-bit max, though I believe that work is still in progress. I wouldn't actually try to put more triangles than that in yet, but the APIs are starting to support it - you'll see in release notes when it's actually ready. For instance, `MeshGL` will stay 32 bit (for convenience with graphics APIs), but we'll probably add a `MeshGL64` version as well.

**Comment by pca006132** [comment] 2024-07-14 02:49
Duplicate of #854

**Closed by pca006132** 2024-07-14 02:49 UTC
