### ISSUE TITLE
Python created object reports as non-manifold.

### ISSUE THREAD

**Issue by briansturgill** [elalish/manifold#768] opened 2024-03-11 01:47 UTC
I'm using Manifold's python API.
Meshlab, PrusaSlicer and trimesh all report the object as non-manifold.

```python
import manifold3d as m
import numpy as np


def wedge(sz, thk):
    vertices = [
        [0, 0, 0],
        [0, -sz, 0],
        [0, 0, sz],
        [thk, 0, 0],
        [thk, -sz, 0],
        [thk, 0, sz],
    ]
    faces = [
        [2, 1, 0],
        [3, 4, 5],
        [0, 3, 2],
        [2, 3, 5],
        [1, 3, 0],
        [1, 4, 3],
        [1, 2, 5],
        [1, 5, 4],
    ]
    mesh = m.Mesh(np.array(vertices, np.float32), np.array(faces, np.uint32))
    w = m.Manifold(mesh)
    return w


d1 = (
    m.Manifold.cube([12 + 4, 16 + 4, 3], center=True)
    - m.Manifold.cube([12, 16, 3], center=True)
).translate([0, 0, 3 / 2])

d2 = m.Manifold.cube([16, 2, 5]).translate([-8, -8 - 2, 3]) - m.Manifold.cube(
    [3, 3, 2]
).translate([-3 / 2, -8, 4])
d3 = m.Manifold.cube([16, 2, 5]).translate([-8, 8, 3]) - m.Manifold.cube(
    [3, 3, 2]
).translate([-3 / 2, 8, 4])
w1 = wedge(5, 2).translate([-8, 8, 3])
w2 = wedge(8, 2).translate([-8, -8 - 2, 0])
w3 = wedge(5, 2).translate([8 - 2, 8, 3])
w4 = wedge(8, 2).translate([8 - 2, -8 - 2, 0])

out = d1 + d2 + d3 + w1 + w2 + w3 + w4

import trimesh

mesh = out.to_mesh()
if mesh.vert_properties.shape[1] > 3:
    vertices = mesh.vert_properties[:, :3]
else:
    vertices = mesh.vert_properties
mesh_output = trimesh.Trimesh(vertices=vertices, faces=mesh.tri_verts)
if not mesh_output.is_watertight:
    print("WARNING: output mesh is not watertight")
trimesh.exchange.export.export_mesh(mesh_output, "/tmp/mesh.obj", "obj")
```

**Comment by pca006132** [comment] 2024-03-11 02:46
Interesting, will have a look at this later.

**Comment by pca006132** [comment] 2024-03-11 04:18
Your `wedge` object is a negative volume, which is not handled properly for now (#745).
You can fix this by flipping the first and second index for every face in `wedge`.

Closing as duplicate of #745.

**Closed by pca006132** 2024-03-11 04:18 UTC

**Comment by briansturgill** [comment] 2024-03-11 14:31
@pca006132 Thanks much!
