### ISSUE TITLE
Python binding needs two import call

### ISSUE THREAD

**Issue by Nosenzor** [elalish/manifold#785] opened 2024-04-09 08:43 UTC
This a minor issue.
Oddly the manifold import need to be done twice otherwise it fails at usage.

```
import manifold3d
from manifold3d import Manifold, Mesh
```
A single of those two lines should be enough.

Despite that you have a new happy user  for the boolean :-)

**Comment by pca006132** [comment] 2024-04-09 08:52
Can you give an example failure? We never had this issue before, our CI only imports python binding once.

**Comment by Nosenzor** [comment] 2024-04-10 15:39
And if do only
`from manifold3d import Manifold, Mesh`
I have this error :
```

    def trimesh_to_manifold3d(mesh):
>     manifold=Manifold(manifold3d.Mesh(vert_properties=np.asarray(mesh.vertices), tri_verts=np.asarray(mesh.faces)))
E     NameError: name 'manifold3d' is not defined
```

**Comment by pca006132** [comment] 2024-04-10 16:22
This is a python thing, in the first example you only imported `manifold3d`, and in the other example you imported `Manifold` and `Mesh` in `manifold3d`. Try

```python
import manifold3d

def trimesh_to_manifold3d(mesh):
    manifold=manifold3d.Manifold(manifold3d.Mesh(vert_properties=np.asarray(mesh.vertices), tri_verts=np.asarray(mesh.faces)))
```

or

```python
from manifold3d import Manifold, Mesh

def trimesh_to_manifold3d(mesh):
    manifold=Manifold(Mesh(vert_properties=np.asarray(mesh.vertices), tri_verts=np.asarray(mesh.faces)))
```

Anyway, closing as this is not a bug.

**Closed by pca006132** 2024-04-10 16:22 UTC
