### ISSUE TITLE
Better management of 3rd party libraries

### ISSUE THREAD

**Issue by kintel** [elalish/manifold#942] opened 2024-09-20 02:31 UTC
Was originally related to Clipper, edited to capture the overall challenge:

The goal is to build and install manifold from source, then utilizing the installed manifold in apps when possible.

I believe the challenge boils down to:
* When building and installing manifold, if any 3rd party dependency isn't found at build time, the manifold build system will _download_, _build_ and _install_ the 3rd party dependencies, as full dev packages (libs + headers + config macros).
* When re-building and re-installing manifold, since (possibly older version of) 3rd party libraries are already present in the install location, no attempt is used to rebuild these libraries, despite them originating from the manifold build system.

This causes some potential friction related to versioning of 3rd party dependencies as we cannot trust that these will be kept at the recommended version encoded in manifold's build system.

The workaround is to, when installing manifold, always install all 3rd party dependencies separately, and make sure manifold doesn't try to manage them internally. This is not configurable today, so care must be taken to inspect the build logs.

Quesions/suggestions:
* Is there a way of hiding the 3rd party binaries in the install location to make sure they are truly private to manifold? ..and while at it don't attempt reusing binaries when rebuilding manifold (unless they're actually the same version/git hash as required)? One typical way of solving this is to build dependencies statically and linking them to the main manifold library, but it might be hard to waterproof this.
* Could we add cmake flags to avoid automatically downloading and building dependencies? The goal is to get a hard failure if dependencies are missing, making it easier for package managers to handle.
* Similar to above, would it make sense to add flags to _force_ download of 3rd party dependencies to avoid picking up older versions from the system?
* There are no version requirements for looking up 3rd party libraries, but when downloading, specific versions are requested. Is this correct behavior or is there a way of unifying lookup vs. download?

**Comment by pca006132** [comment] 2024-09-20 02:35
Probably just remove this: https://github.com/elalish/manifold/blob/master/manifoldDeps.cmake#L44

**Comment by kintel** [comment] 2024-09-20 02:37
Let's wait until I've gone through an entire install cycle. Since clipper shared objects are installed, the installer already leaks that into the system we're installing on. I should probably look into installing clipper separately and see how that flies.

**Comment by kintel** [comment] 2024-09-22 13:27
@hzeller ..in case you have any insights from packaging manifold in NixOS

**Comment by pca006132** [comment] 2024-09-22 13:29
nixos installs clipper2 as system dependency

**Comment by pca006132** [comment] 2024-09-22 16:57
Thinking about this for a while...

1. It may make sense to add cmake flags for downloading and building dependencies, and default to no download.
2. For dependencies like clipper2, we can probably just statically link it. This avoids potential version issues (different path order can lead to different lookup results, which will be a pain to debug across distros), and avoids the need to install the dependency.
3. For things like tbb, we probably should ask the user to install it manually. TBB explicitly discourages static linking as it may do weird stuff, though we do statically link it for our python builds and so far there is no issue... Not sure how hard will it be to override the system version, not familiar with how rpath management in cmake.
4. We download a specific version because the master branch of those projects may not be release candidates and can contain serious bugs, and pinning the version down can help us make the CI reproducible. We haven't yet checked for version compatibility, but in general if it builds, it should work. Some libraries, such as clipper2 may require new versions for certain bug fix, but they are usually not related to manifold.

**Comment by pca006132** [comment] 2024-09-22 16:58
And we should probably make `MANIFOLD_PAR` `ON/OFF` as well, we no longer have different backends.

**Comment by hzeller** [comment] 2024-09-22 19:03
In NixOS, clipper2 is a system dependency, and from what I know from the spirit of other distros, they will have that as strong preference to use a system dependency as well.

In _particular_ build systems for distros do not like if the build system of a program 'sideloads' stuff from the net while building. NixOS and Debian for instance (possibly others, but these are the ones I am familiar with) cap the network connection during the build to prevent that.
Anything that should go in is then probably better managed as submodule or explicit 'you need this installed on your system to build' documentation.

Problem with too many submodules is that (to my knowledge) it is not simple to selectively just get some submodules on an initial recursive clone, if not all of them are needed; for instance `mimalloc` and `OpenCSG` should be readily available as system libraries on distros, so most of the packaging would git clone these, but then not use them.

**Comment by kintel** [comment] 2024-09-22 19:25
Thanks @hzeller - I guess I was hoping to build manifold externally as a quick win. I'll probably go back and package each dependency manually. Context: Some libraries, like manifold, Clipper, OpenCSG, are not yet very widely used, so we practically have to manage building these for our target environments, especially for macOS and Windows.

Note: OpenCSG is a special case, where distro packages, and sometimes releases themselves, are too outdated, and we need to build ourselves to be able to obtain a useable build.

**Comment by pca006132** [comment] 2024-09-23 05:17
> Note: OpenCSG is a special case, where distro packages, and sometimes releases themselves, are too outdated, and we need to build ourselves to be able to obtain a useable build.

Also concerned about this for manifold as well. Manifold is developing relatively quickly comparing to the package update frequency of mainstream distros, perhaps only things like AUR and nixpkgs can keep this up-to-date enough.

**Comment by kintel** [comment] 2024-09-24 15:42
A cleaner approach (for manifold) could be to separate out all CI-related concerns from the main CMake build system, and make the CMake build a bit leaner. It would, however, require to manage dependencies as a separate step, and rely on find macros for everything. It's a bit of work, admittedly, but as Manifold is getting to the point where it's being packaged separately, a bunch of people will run into this and need some solution.

Sometimes, starting from scratch is even preferable as there may be significant old cruft hiding in CMake files :)

Manifold is a bit more complex, of course, as it targets WASM as well as multiple language bindings as part of the main build system. Also, the "new dev getting started" experience is currently pretty good as people don't need to deal with deps very much.

**Comment by pca006132** [comment] 2024-09-24 15:47
I think the dependency related code are in https://github.com/elalish/manifold/blob/master/manifoldDeps.cmake, should be relatively easy to just add some if statements to block automatic downloading of dependencies for example.

Agreed that we may want to start from scratch for cmake, some choices worked fine for us but may be causing issue for users or for future updates. For example, we use wildcard for gathering the source files, but apparently this is discouraged as cmake will not be getting the newly added files later automatically... CMake is just weird.

**Comment by starseeker** [comment] 2024-09-25 18:07
My perspective on this is a little skewed, since BRL-CAD has a rather elaborate system to manage massive dependency requirements and allow either bundled or system versions (see https://github.com/BRL-CAD/bext if you're curious - it's SERIOUS overkill for most projects, including Manifold - you only want to do something like that if you *really* need it.)

Initially I too just made my own build setup for Manifold and embedded the needed dependencies directly in its tree for simplicity, but I'm in the process of testing out switching to a vanilla Manifold build.  In our case we want to have all dependencies not being build as part of an individual dependency set up for use ahead of time, so I bit the bullet and integrated GLM and Clipper2 into our dependency list (we already had assimp).  As long as a new enough CMake is used, it is possible to use *_ROOT variables to precisely tell the Manifold build where to go hunting for its dependencies, which is a fairly simple and clean answer as long as you can set up the dependencies ahead of time.

Speaking selfishly, I would like an option to disable Manifold's automatic downloading, since in our use case if we haven't set up the dependencies it needs correctly ourselves that's a problem and we don't want Manifold to mask that by solving the issue with a local copy.

Conversely, if Manifold *needs* a particular version of (say) Clipper2 and a default system version isn't expected to work, it might be better to bundle and build that particular version directly as part of the relevant library. I'd be surprised if that's the case for Manifolds current dependencies though - is there any risk that a specific version of Clipper2 might be needed?  ( I note that the latest Clipper2 release appears newer than the SHA1 referenced in Manifold's download, but I suspect that was probably specified to get an upstream fix that hadn't yet been released and it could probably be updated to the latest released version now?)

**Comment by pca006132** [comment] 2024-09-26 02:14
> I would like an option to disable Manifold's automatic downloading

Sure, I think this is what most downstream consumers want.

> Conversely, if Manifold needs a particular version of (say) Clipper2 and a default system version isn't expected to work, it might be better to bundle and build that particular version directly as part of the relevant library. I'd be surprised if that's the case for Manifold's current dependencies though - is there any risk that a specific version of Clipper2 might be needed? ( I note that the latest Clipper2 release appears newer than the SHA1 referenced in Manifold's download, but I suspect that was probably specified to get an upstream fix that hadn't yet been released and it could probably be updated to the latest released version now?)

No, we don't really need a particular version of clipper2, as long as it can be built. We fix the SHA1 because we need that to make the CI job reproducible, but in general we rarely update those SHA1 hashes unless things break...

**Comment by elalish** [comment] 2024-09-30 04:32
This is a pretty long thread with a lot of good ideas, but I think at least the majority has been addressed in #961, particularly that auto-downloads can be disabled with a CMake flag now. I'm going to close this, but feel free to open a new issue with any specifics here that haven't been adequately solved yet.

**Closed by elalish** 2024-09-30 04:32 UTC
