### ISSUE TITLE
Triangulate bug: Two separate polygons

### ISSUE THREAD

**Issue by kintel** [elalish/manifold#790] opened 2024-04-13 14:57 UTC
Adding two separate outlines to `Polygons` and tessellating sometimes causes very odd triangulations.

Example test case:
```
TEST(Polygon, Separate_Quad_And_Tri) {
  Polygons polys;
  polys.push_back({{3, 1}, {3, 0}, {2, 0}});
  polys.push_back({{0.8, 0.8}, {1, 1}, {0, 1}, {0.2, 0.8}});
  TestPoly(polys, 3, 0.00145);
}
```

This should yield 3 triangles (one triangulated quad plus one triangle), but:
```
Expected equality of these values:
  triangles.size()
    Which is: 10
  2 * expectedNumTri
    Which is: 6
```

Side note: These tests only measure the number of triangles, which may make the tests very brittle.

**Comment by elalish** [comment] 2024-04-14 04:47
When we run our tests, we run them with `params.intermediateChecks = true`, which asserts the manifoldness of each triangulation, and with `params.processOverlaps = false`, which checks that every triangle is CCW. Those should catch this well before the number of triangles check - would you mind adding this test as a PR; then we should see that behavior on the CI. 

This seems like a pretty basic error - I'm surprised our existing corpus doesn't catch it.

**Comment by elalish** [comment] 2024-04-14 04:49
Not that it should matter, but that's a surprisingly wide precision you've specified - is that necessary to repro?

**Comment by kintel** [comment] 2024-04-14 13:39
I opened a PR with the failure case. The precision setting isn't needed, I just inherited the argument from surrounding tests in my first repro.

I experience lots of errors like this in OpenSCAD (first attempt at using the triangulator). This is the most trivial one I could find, but it's probably good to start off fixing this before potentially registering a bunch of duplicates.

**Comment by elalish** [comment] 2024-04-14 21:55
Closing as expected behavior since this is an invalid polygon.

**Closed by elalish** 2024-04-14 21:55 UTC

**Comment by kintel** [comment] 2024-04-14 22:03
Thanks for taking a look - I'll fix my upstream issue and run my larger tests :)
